[package]
name = "sane-circuit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "The circuit representation of SANE: elements, devices, subcircuits, nodes and values"

[dependencies]
rsdag.workspace = true
sane-core.workspace = true
sane-device = { path = "../device" }
sane-veriloga = { path = "../veriloga" }
rustc-hash.workspace = true

[lints]
workspace = true
